/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeRouteImport } from './routes/me'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchMediaIdRouteImport } from './routes/watch.$mediaId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMediaIdRoute = WatchMediaIdRouteImport.update({
  id: '/watch/$mediaId',
  path: '/watch/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/watch/$mediaId': typeof WatchMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/watch/$mediaId': typeof WatchMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/watch/$mediaId': typeof WatchMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/me' | '/settings' | '/watch/$mediaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/me' | '/settings' | '/watch/$mediaId'
  id: '__root__' | '/' | '/account' | '/me' | '/settings' | '/watch/$mediaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  MeRoute: typeof MeRoute
  SettingsRoute: typeof SettingsRoute
  WatchMediaIdRoute: typeof WatchMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$mediaId': {
      id: '/watch/$mediaId'
      path: '/watch/$mediaId'
      fullPath: '/watch/$mediaId'
      preLoaderRoute: typeof WatchMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  MeRoute: MeRoute,
  SettingsRoute: SettingsRoute,
  WatchMediaIdRoute: WatchMediaIdRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
