/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeRouteImport } from './routes/me'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchMediaIdRouteImport } from './routes/watch.$mediaId'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiPostprocessRouteImport } from './routes/api/postprocess'
import { Route as ApiYoutubeTranscribeRouteImport } from './routes/api/youtube/transcribe'
import { Route as ApiYoutubeResolveRouteImport } from './routes/api/youtube/resolve'
import { Route as ApiYoutubeCaptionsRouteImport } from './routes/api/youtube/captions'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMediaIdRoute = WatchMediaIdRouteImport.update({
  id: '/watch/$mediaId',
  path: '/watch/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostprocessRoute = ApiPostprocessRouteImport.update({
  id: '/api/postprocess',
  path: '/api/postprocess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeTranscribeRoute = ApiYoutubeTranscribeRouteImport.update({
  id: '/api/youtube/transcribe',
  path: '/api/youtube/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeResolveRoute = ApiYoutubeResolveRouteImport.update({
  id: '/api/youtube/resolve',
  path: '/api/youtube/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeCaptionsRoute = ApiYoutubeCaptionsRouteImport.update({
  id: '/api/youtube/captions',
  path: '/api/youtube/captions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/api/postprocess': typeof ApiPostprocessRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/watch/$mediaId': typeof WatchMediaIdRoute
  '/api/youtube/captions': typeof ApiYoutubeCaptionsRoute
  '/api/youtube/resolve': typeof ApiYoutubeResolveRoute
  '/api/youtube/transcribe': typeof ApiYoutubeTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/api/postprocess': typeof ApiPostprocessRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/watch/$mediaId': typeof WatchMediaIdRoute
  '/api/youtube/captions': typeof ApiYoutubeCaptionsRoute
  '/api/youtube/resolve': typeof ApiYoutubeResolveRoute
  '/api/youtube/transcribe': typeof ApiYoutubeTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/api/postprocess': typeof ApiPostprocessRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/watch/$mediaId': typeof WatchMediaIdRoute
  '/api/youtube/captions': typeof ApiYoutubeCaptionsRoute
  '/api/youtube/resolve': typeof ApiYoutubeResolveRoute
  '/api/youtube/transcribe': typeof ApiYoutubeTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/me'
    | '/settings'
    | '/api/postprocess'
    | '/api/transcribe'
    | '/watch/$mediaId'
    | '/api/youtube/captions'
    | '/api/youtube/resolve'
    | '/api/youtube/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/me'
    | '/settings'
    | '/api/postprocess'
    | '/api/transcribe'
    | '/watch/$mediaId'
    | '/api/youtube/captions'
    | '/api/youtube/resolve'
    | '/api/youtube/transcribe'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/me'
    | '/settings'
    | '/api/postprocess'
    | '/api/transcribe'
    | '/watch/$mediaId'
    | '/api/youtube/captions'
    | '/api/youtube/resolve'
    | '/api/youtube/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  MeRoute: typeof MeRoute
  SettingsRoute: typeof SettingsRoute
  ApiPostprocessRoute: typeof ApiPostprocessRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  WatchMediaIdRoute: typeof WatchMediaIdRoute
  ApiYoutubeCaptionsRoute: typeof ApiYoutubeCaptionsRoute
  ApiYoutubeResolveRoute: typeof ApiYoutubeResolveRoute
  ApiYoutubeTranscribeRoute: typeof ApiYoutubeTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$mediaId': {
      id: '/watch/$mediaId'
      path: '/watch/$mediaId'
      fullPath: '/watch/$mediaId'
      preLoaderRoute: typeof WatchMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postprocess': {
      id: '/api/postprocess'
      path: '/api/postprocess'
      fullPath: '/api/postprocess'
      preLoaderRoute: typeof ApiPostprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/transcribe': {
      id: '/api/youtube/transcribe'
      path: '/api/youtube/transcribe'
      fullPath: '/api/youtube/transcribe'
      preLoaderRoute: typeof ApiYoutubeTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/resolve': {
      id: '/api/youtube/resolve'
      path: '/api/youtube/resolve'
      fullPath: '/api/youtube/resolve'
      preLoaderRoute: typeof ApiYoutubeResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/captions': {
      id: '/api/youtube/captions'
      path: '/api/youtube/captions'
      fullPath: '/api/youtube/captions'
      preLoaderRoute: typeof ApiYoutubeCaptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  MeRoute: MeRoute,
  SettingsRoute: SettingsRoute,
  ApiPostprocessRoute: ApiPostprocessRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  WatchMediaIdRoute: WatchMediaIdRoute,
  ApiYoutubeCaptionsRoute: ApiYoutubeCaptionsRoute,
  ApiYoutubeResolveRoute: ApiYoutubeResolveRoute,
  ApiYoutubeTranscribeRoute: ApiYoutubeTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
