/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerFileIdRouteImport } from './routes/player.$fileId'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiPostprocessRouteImport } from './routes/api/postprocess'
import { Route as ApiPerformanceRouteImport } from './routes/api/performance'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiYoutubeResolveRouteImport } from './routes/api/youtube/resolve'
import { Route as ApiYoutubeCaptionsRouteImport } from './routes/api/youtube/captions'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerFileIdRoute = PlayerFileIdRouteImport.update({
  id: '/player/$fileId',
  path: '/player/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostprocessRoute = ApiPostprocessRouteImport.update({
  id: '/api/postprocess',
  path: '/api/postprocess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPerformanceRoute = ApiPerformanceRouteImport.update({
  id: '/api/performance',
  path: '/api/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeResolveRoute = ApiYoutubeResolveRouteImport.update({
  id: '/api/youtube/resolve',
  path: '/api/youtube/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeCaptionsRoute = ApiYoutubeCaptionsRouteImport.update({
  id: '/api/youtube/captions',
  path: '/api/youtube/captions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/performance': typeof ApiPerformanceRoute
  '/api/postprocess': typeof ApiPostprocessRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/player/$fileId': typeof PlayerFileIdRoute
  '/api/youtube/captions': typeof ApiYoutubeCaptionsRoute
  '/api/youtube/resolve': typeof ApiYoutubeResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/performance': typeof ApiPerformanceRoute
  '/api/postprocess': typeof ApiPostprocessRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/player/$fileId': typeof PlayerFileIdRoute
  '/api/youtube/captions': typeof ApiYoutubeCaptionsRoute
  '/api/youtube/resolve': typeof ApiYoutubeResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/performance': typeof ApiPerformanceRoute
  '/api/postprocess': typeof ApiPostprocessRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/player/$fileId': typeof PlayerFileIdRoute
  '/api/youtube/captions': typeof ApiYoutubeCaptionsRoute
  '/api/youtube/resolve': typeof ApiYoutubeResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/settings'
    | '/api/health'
    | '/api/performance'
    | '/api/postprocess'
    | '/api/transcribe'
    | '/player/$fileId'
    | '/api/youtube/captions'
    | '/api/youtube/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/settings'
    | '/api/health'
    | '/api/performance'
    | '/api/postprocess'
    | '/api/transcribe'
    | '/player/$fileId'
    | '/api/youtube/captions'
    | '/api/youtube/resolve'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/settings'
    | '/api/health'
    | '/api/performance'
    | '/api/postprocess'
    | '/api/transcribe'
    | '/player/$fileId'
    | '/api/youtube/captions'
    | '/api/youtube/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPerformanceRoute: typeof ApiPerformanceRoute
  ApiPostprocessRoute: typeof ApiPostprocessRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  PlayerFileIdRoute: typeof PlayerFileIdRoute
  ApiYoutubeCaptionsRoute: typeof ApiYoutubeCaptionsRoute
  ApiYoutubeResolveRoute: typeof ApiYoutubeResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$fileId': {
      id: '/player/$fileId'
      path: '/player/$fileId'
      fullPath: '/player/$fileId'
      preLoaderRoute: typeof PlayerFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postprocess': {
      id: '/api/postprocess'
      path: '/api/postprocess'
      fullPath: '/api/postprocess'
      preLoaderRoute: typeof ApiPostprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/performance': {
      id: '/api/performance'
      path: '/api/performance'
      fullPath: '/api/performance'
      preLoaderRoute: typeof ApiPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/resolve': {
      id: '/api/youtube/resolve'
      path: '/api/youtube/resolve'
      fullPath: '/api/youtube/resolve'
      preLoaderRoute: typeof ApiYoutubeResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/captions': {
      id: '/api/youtube/captions'
      path: '/api/youtube/captions'
      fullPath: '/api/youtube/captions'
      preLoaderRoute: typeof ApiYoutubeCaptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPerformanceRoute: ApiPerformanceRoute,
  ApiPostprocessRoute: ApiPostprocessRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  PlayerFileIdRoute: PlayerFileIdRoute,
  ApiYoutubeCaptionsRoute: ApiYoutubeCaptionsRoute,
  ApiYoutubeResolveRoute: ApiYoutubeResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
